### PR TITLE
Typo - Update README.md

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Before merging. About "`@vars` would be deprecated" should that be "is" or will"? I could add the correct change for that to this PR, or not. Also I noticed "newdefault" that I had missed, and it should be two words, right...

**Comment by jverzani** [comment]
Thanks! I just had fixed this in #19. But if you had other suggestions, let me know. I'm quite happy to get them,

**Comment by PallHaraldsson** [comment]
You mean "`@vars` of `SymPy` is not provided; use the more powerful `@syms` macro only", I can add change to that in the README and fix the other thing, then merge would you want that?

**Comment by jverzani** [comment]
That would be great. Thanks!

**Review by jverzani — COMMENTED** [review]
Thanks!!

**Pull request merged**
